### ISSUE TITLE
Add Option to create from JDK

### ISSUE THREAD

**Issue by hadimansuri** [paketo-buildpacks/spring-boot#71]
## What happened?
I have a spring-boot WebFlux project, I add the following dependency:
```
       <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-tools</artifactId>
        </dependency>
```
and create docker image using:
 `./mvnw clean spring-boot:build-image`
When I run the created image I get this error:
```
Setting Active Processor Count to 8
Calculating JVM memory based on 3674572K available memory
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx3225867K -XX:MaxMetaspaceSize=141504K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 3674572K, Thread Count: 50, Loaded Class Count: 22569, Headroom: 0%)
Adding 129 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -agentpath:/layers/paketo-buildpacks_bellsoft-liberica/jvmkill/jvmkill-1.16.0-RELEASE.so=printHeapHistogram=1 -XX:ActiveProcessorCount=8 -XX:MaxDirectMemorySize=10M -Xmx3225867K -XX:MaxMetaspaceSize=141504K -XX:ReservedCodeCacheSize=240M -Xss1M -Dorg.springframework.cloud.bindings.boot.enable=true
19:29:36.203 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.RuntimeException: Failed to init Reactor's debug agent
        at org.springframework.boot.reactor.DebugAgentEnvironmentPostProcessor.postProcessEnvironment(DebugAgentEnvironmentPostProcessor.java:52)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at com.gfg.sc.filemanager.FileManagerApplication.main(FileManagerApplication.java:17)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.reactor.DebugAgentEnvironmentPostProcessor.postProcessEnvironment(DebugAgentEnvironmentPostProcessor.java:49)
        ... 25 common frames omitted
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
        at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:602)
        at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586)
        at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538)
        at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515)
        at reactor.tools.agent.ReactorDebugAgent.init(ReactorDebugAgent.java:56)
        ... 30 common frames omitted
```
If I create the image using the following `Dcokerfile` it works fine:

```
FROM adoptopenjdk/openjdk15
COPY target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]

```
Because `Reactor's debug agent` requires the `jdk.attach` java module which should be included in the JRE.
I can suggest adding an environment variable `$RUN_ON_JDK` or `FROM_JDK` which runs the application using JDK instead of JRE.
The optimal case is to detect required java modules and add them to JRE. [see](https://stackoverflow.com/a/66691432)
I think It is also related to [bellsoft-liberica](https://github.com/paketo-buildpacks/bellsoft-liberica)

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by scottfrederick** [comment]
The choice of the JRE or JDK to install is entirely up to the buildpacks that participate in building the image, and there is currently not a way for Spring Boot to instruct the Paketo builder or Java buildpacks to install a JDK instead of a JRE. There is a [related issue](https://github.com/paketo-buildpacks/bellsoft-liberica/issues/4) in the Bellsoft Liberica buildpack, you might want to add your use case as a comment there.
